### ISSUE TITLE
Consent status is confusing

### ISSUE THREAD

**Issue by 00christian00** [appodeal/cmp-unity-plugin#1]
Hello,
I followed the documentation and it took me a whole day to understand how the consent plugin work.
I was testing by refusing the consent and then checking the consent status and I would always get "obtained".
I had to debug the whole SDK to understand what is happening. 
Basically there is nothing in the API right now to see if the user did actually consent or not?
This is very confusing, why is it so? It should be explained properly and I think it would be better to just add a "not consented" status or a more fine grained status. Anyway this should have been explained in the docs.
I could use the playerprefs value, but I am not sure it is the same for all platform or just something used for the editor dummy form.

**Comment by dmitriifeshchenko** [comment]
Hi, @00christian00!

This Unity plugin is only a wrapper over native Android and iOS CMP SDKs. All the changes first have to be made on that level.

But as for your question, our CMP is compliant with TCF v2 and is certified by IAB and Google. This version of TCF is made with privacy in mind, so there is no way to check whether the consent was granted. You can check the [Google UMP doc](https://developers.google.com/admob/android/privacy/api/reference/com/google/android/ump/ConsentInformation.ConsentStatus.html#constants) and you'll find that their statuses are the same.

As per [our documentation](https://docs.appodeal.com/unity/data-protection/gdpr-and-ccpa), you need to call the `RequestConsentInfoUpdate` method and listen to the events. Then you check the consent status. If it's `NotRequired` or `Obtained` you can initialize ads, otherwise, you need to show a consent form.

**Comment by 00christian00** [comment]
Hi [DmitriiFeshchenko](https://github.com/DmitriiFeshchenko),
I understand now but the documentation is lacking, you can't expect devs to know the whole TCF v2 before integrating the SDK.
Also the documentation never mentions that you need to call RequestConsentInfoUpdate and listen to the events to get the status. It only says to call it to change the consent status.

Also regarding the privacy issue of knowing the real consent, I made some research and Google sdk says that by TCFv2 rules the result of the form choices is encoded in a string freely readable:
https://developers.google.com/admob/android/privacy/gdpr?hl=it#how_to_read_consent_choices

So it is not a matter of privacy.

**Comment by dmitriifeshchenko** [comment]
It's important to mention that our SDK handles the consent request automatically by default. For most use cases it should be enough. This is one of the main reasons why the manual flow isn't thoroughly documented at the moment. Anyway, I'll let the team responsible for the docs know that this one is not clear enough.

Nowadays privacy is always a matter. Indeed you can read iab tcf strings from prefs. But as you know, it's more complex than just a boolean. Thus we cannot have those `ConsentGranted` and `ConsentDenied` statuses anymore.

**Comment by 00christian00** [comment]
I think there is a bug in the way the unknown status is handled. I haven't been able to narrow down what cause it, but sometime I have unknown status and I cannot show the consent form because it returns an error that it is not needed. I am calling RequestConsentInfoUpdate before. 
Revoking the consent again seem to fix things, but I don't understand why I get stuck in this "limbo".

**Comment by 00christian00** [comment]
![image](https://github.com/user-attachments/assets/d06efbb8-2181-4a72-ac61-7ca3b3a5eb15)
Am I doing something wrong? Do I need to initialize something to get the status?
As you can see from the log the status is reported unknown initially and it return the error "not required". Then it suddenly shows the status is obtained although I didn't complete any form.

**Comment by 00christian00** [comment]
Spent a whole day and I still cannot get it to work. As it is right now the sdk is really incomplete.
All the api calls are synchronous but to work in device they must have asynchronous wrapper. 
I wrote the code on the editor and was working fine but then and I went crazy trying to understand why it wasn't working. 
On device all api calls have some kind of delay and cannot be used synchronously, this is not explained anywhere.
There is quite a bit of additional code to write to have a working setup.

**Comment by Rabadash8820** [comment]
I know this Issue is closed, but I would second that the docs are rather confusing about this. In particular, it's not clear how to update consent for data providers that are _not_ registered with TCF, like Unity Analytics. The only solution I've thought of is to have a separate consent dialog for the non-TCF providers before the CMP dialog for ad providers, but having two separate dialogs is not ideal...

**Comment by dmitriifeshchenko** [comment]
Thanks for your input, @Rabadash8820. I've forwarded your message to the team responsible for docs. The task is there it's just a low priority at the moment.
